sudo: required


services:
  - mariadb

  - docker


language: node_js


node_js:

- "node"

- "9"

install:

  - npm install
  - npm add request
  - npm install mysql
  - cd telebot/
  - cd Bot/


branches:

  only:

  - dev

script:

  - node botmaria.js