sudo: required


services:
  - docker


language: node_js


node_js:

- "node"

- "9"

before_install:
  - cd mariaDB
  - docker-compose up -d
  - cd ..
  - cd telebot

install:

  - npm install
  - npm add request
  - npm install mysql


branches:

  only:

  - dev

script:

  - node Bot/botmaria.js