sudo: required


services:
  - mariadb

  - docker


language: node_js


node_js:

- "node"

- "9"

before_install:

  - cd mariaDB
  - docker ps
  - docker-compose up -d
  - docker ps
  - sudo docker exec -it mariadb_mysql_1 mysql -uroot -p
  - cd ..

install:

  - npm install
  - npm add request
  - npm install mysql


branches:

  only:

  - dev

script:

  - node botmaria.js