sudo: required


services:
  - mariadb

  - docker


language: node_js


node_js:

- "node"

- "9"

before_install:
  - cd telebot

install:

  - npm install
  - npm add request
  - npm install mysql


branches:

  only:

  - dev

cache:

  directories:

    - node_modules

script:

    - npm run test
    